### PR TITLE
docs: added few Frontend technologies to data.json

### PR DESCRIPTION
**Pull request by zabihshaik**
Hey Zhu!

Saw your LinkedIn post about Frontend Encyclopedia. Thanks for providing all the frontend related technologies at one place. Thought of adding few more, and contribute to the repository.

Thanks again.

### CODE REVIEW

**Comment by paradite** [comment]
Hi @zabihshaik this looks good. But can you correct the name of Ionic to its official name? 

I would like to keep the name format correct and accurate.

**Comment by paradite** [comment]
Looking at its docs, Ionic appears to be the official name being referred to multiple times. 

https://ionicframework.com/docs/

**Comment by zabihshaik** [comment]
@paradite Yeah Sure. Will update it as Ionic. Thanks for the prompt response. Hope that, rest everything is fine.

**Comment by zabihshaik** [comment]
Done it. Do I need to raise another PR or is it enough?

**Comment by paradite** [comment]
> Done it. Do I need to raise another PR or is it enough?

It's enough. I will update the README and categories manually.

**Comment by zabihshaik** [comment]
OK. Thanks @paradite 👍

**Pull request merged**
