### PR TITLE
added new entries

### PR DESCRIPTION
**Pull request by deepareddy-hub**

### CODE REVIEW

**Comment by paradite** [comment]
Hi. Sorry I am not accepting items that are not following the criteria outlined here:

https://github.com/paradite/frontend-encyclopedia#criteria-for-inclusion

If something is not specific to frontend and not many frontend engineers are using, it shouldn't be added. For example, anything related to Java, message queue, streams, data science, ORM, native mobile app development, another programming language that is not JS/TS.

**Comment by paradite** [comment]
Out of the terms you added, I think only `Visual Studio Code` would fit the criteria. Please remove the rest.

**Comment by deepareddy-hub** [comment]
sure

**Comment by paradite** [comment]
Ok I will manually update the markdown files once merged.

**Pull request merged**
