### PR TITLE
Added Author and Author URL for each record

### LINKED ISSUE #24: Add author
We may need two more optional fields: `author` as string and `author_url` as an URL.

Also need to update `generate.js` to render the fields

### PR DESCRIPTION
**Pull request by RamGoel**
Fixes #24

### CODE REVIEW

**Comment by RamGoel** [comment]
Please Squash the commits before merging. @paradite

**Comment by paradite** [comment]
Wow that is a lot of changes. Thanks for the effort.

I think it is a good PR, I just want one modification before I merge this: can you make the author field optional? i.e. it should not add the link if there is no author. Also, for some terms like accessibility we can leave out the author field instead of having N/A.

I will do some minor fixes after the merge if any.

**Comment by RamGoel** [comment]
@paradite SURE

**Comment by RamGoel** [comment]
@paradite I have added a commit for the proposed change. The author need to be displayed in only Readme.md or other files as well.

**Comment by paradite** [comment]
merged. i will do some minor fixes.

**Pull request merged**
