### PR TITLE
Saber changes

### PR DESCRIPTION
**Pull request by ahmed0saber**

### CODE REVIEW

**Comment by ahmed0saber** [comment]
Hello @paradite , you can accept without years right now, I'll add years later, but first accept to avoid coming merge conflicts, adding years will not cause a conflict.

**Comment by paradite** [comment]
Hi @ahmed0saber. Thanks for your additions.

However, I want to keep this repo focused on frontend technologies and concepts, so general concepts like **Algorithms** and **Anti-Patterns**, which are also applicable to backend, should not be added.

Please remove those terms from the PR.

**Comment by ahmed0saber** [comment]
@paradite , thanks for letting me know, I've removed them.

**Comment by paradite** [comment]
Thank you. Merged.

**Pull request merged**
