### PR TITLE
feat: formatting

### PR DESCRIPTION
**Pull request by yefreescoding**
I updated the year_created and year_deprecated for the terms.

I obtained the information by searching the official documentation of each technology. I only added the ones with clear information about the year they were created.

### CODE REVIEW

**Comment by paradite** [comment]
Hi, can you add your sources in the description of the PR?

I checked https://en.wikipedia.org/wiki/Cascading_Style_Sheets and CSS was released in 1996, not 1994. I think I would like to consider the first release date, not when it was first proposed.

**Comment by paradite** [comment]
On second thought, maybe it is better if we have another field like "year_created_source" to record the source of this information. It can be just in `data.json` without being displayed to the user.

**Comment by yefreescoding** [comment]
Perfect, I could add "year_created_source" to each one of the technologies I changed. And I'll fix the CSS field.

**Comment by yefreescoding** [comment]
d

**Comment by paradite** [comment]
looks good. merged! feel free to raise another PR to update the other terms.

**Pull request merged**
